---
sudo: false
addons:
  apt:
    packages:
      - aspell
      - aspell-en
language: perl
perl:
  - blead
  - blead-thr
  - dev
  - dev-thr
  - 5.26.1
  - 5.26.1-thr
  - 5.24.2
  - 5.24.2-thr
  - 5.22.4
  - 5.22.4-thr
  - 5.20.3
  - 5.20.3-thr
  - 5.18.3
  - 5.18.3-thr
  - 5.16.3
  - 5.16.3-thr
  - 5.14.4
  - 5.14.4-thr
cache:
  directories:
    - $HOME/perl5
matrix:
  allow_failures:
    - perl: blead
    - perl: blead-thr
  include:
    - env: COVERAGE=1
      perl: '5.26'
env:
  global:
    - AUTHOR_TESTING=1
    - RELEASE_TESTING=1
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto --always-upgrade-modules
### __app_cisetup__
# ---
# force_threaded_perls: 0
# perl_caching: 1

### __app_cisetup__
